### ISSUE TITLE
vagrant.sh not working on macOS Sierra

### ISSUE THREAD

**Issue by fabianw931** [NateMS/snippets#1]
When I try to run it using

`source vagrant.sh`

I get the following error:

```
-bash: $'\r': command not found
-bash: vagrant.sh: line 25: syntax error: unexpected end of file
```

Line 25 seems to be after the end tag of the script.

Please fix.

**Comment by NateMS** [comment]
hmm, interesting problem, I'll look into it, thanks for reporting.

**Comment by NateMS** [comment]
can you please state your exact OSX version?

**Comment by fabianw931** [comment]
I'm using macOS Sierra version 10.12.3.
Also I'm trying to run the script in a bash shell using bash version 4.4.12(1).

**Comment by fabianw931** [comment]
I was able to fix it. See my pull request.
